from enum import Enum

class ProductionType(Enum):
    FACTORY = "Factory"
    MPF = "MassProductionFactory"
    MANUAL_BUILD = "ManualBuild"
    GARAGE = "Garage"
    CONSTRUCTION_YARD = "ConstructionYard"
    SHIPYARD = "Shipyard"
    FACILITY = "Facility"

class FacilityType(Enum):
    VEHICLE_FACTORY_1 = "FacilityVehicleFactory1"
    VEHICLE_FACTORY_2 = "FacilityVehicleFactory2"
    VEHICLE_FACTORY_3 = "FacilityVehicleFactory3"
    FACTORY_SMALL_ARMS = "FacilityFactorySmallArms"
    FACTORY_AMMO = "FacilityFactoryAmmo"
    REFINERY_COAL = "FacilityRefineryCoal"
    REFINERY_OIL = "FacilityRefineryOil"
    MINE_OIL = "FacilityMineOil"
    REFINERY = "WorldStructureRefinery"
    REFINERY_1 = "FacilityRefinery1"
    REFINERY_2 = "FacilityRefinery2"
    POWER_DIESEL = "FacilityPowerDiesel"
    POWER_OIL = "FacilityPowerOil"
    ROCKET_SITE = "RocketSite"
    CONCRETE_MIXER = "ConcreteMixer"

class ProcessType(Enum):
    DEFAULT = "Default"
    MOTOR_POOL = "MotorPool"
    ARTILLERY_FACTORY = "ArtilleryFactory"
    TANK_ASSEMBLY = "TankAssembly"
    WEAPONS_PLATFORM_ASSEMBLY = "WeaponsPlatformAssembly"
    HEAVY_TANK_ASSEMBLY = "HeavyTankAssembly"
    TRAIN_ASSEMBLY = "TrainAssembly"
    SHIP_ASSEMBLY = "ShipAssembly"
    ROCKET_ASSEMBLY = "RocketAssembly"
    FORGE = "Forge"
    METAL_PRESS = "MetalPress"
    RECYCLER = "Recycler"
    BLAST_FURNACE = "BlastFurnace"
    ENGINEERING_STATION = "EngineeringStation"
    COKE_FURNACE = "CokeFurnace"
    COAL_LIQUIFIER = "CoalLiquifier"
    ADVANCED_COAL_LIQUIFIER = "AdvancedCoalLiquifier"
    REFORMER = "Reformer"
    CRACKING_UNIT = "CrackingUnit"
    PETROCHEMICAL_PLANT = "PetrochemicalPlant"
    SULFURIC_REACTOR = "SulfuricReactor"
    LARGE_SHELL_FACTORY = "LargeShellFactory"
    ROCKET_FACTORY = "RocketFactory"
    TRIPOD_FACTORY = "TripodFactory"
    INFANTRY_AMMO = "InfantryAmmo"
    HEAVY_AMMO = "HeavyAmmo"
    SPECIAL_WEAPONS = "SpecialWeapons"
    UNIFORMS = "Uniforms"
    SMALL_ARMS = "SmallArms"
    HEAVY_ARMS = "HeavyArms"
    SUPPLIES = "Supplies"
    UTILITY = "Utility"
    MEDICAL = "Medical"
    METALWORKS = "Metalworks"

# Example mapping dictionary
PRODUCTION_PROCESS_MAP = {
    "Vehicle::Facility::Base": (FacilityType.VEHICLE_FACTORY_1, ProcessType.DEFAULT),
    "Vehicle::Facility::MotorPool": (FacilityType.VEHICLE_FACTORY_1, ProcessType.MOTOR_POOL),
    "Vehicle::Facility::BatteryLine": (FacilityType.VEHICLE_FACTORY_1, ProcessType.ARTILLERY_FACTORY),
    "Vehicle::Facility::FieldStation": (FacilityType.VEHICLE_FACTORY_1, ProcessType.ARTILLERY_FACTORY),
    "Vehicle::Facility::Tank": (FacilityType.VEHICLE_FACTORY_1, ProcessType.TANK_ASSEMBLY),
    "Vehicle::Facility::WeaponsPlatform": (FacilityType.VEHICLE_FACTORY_1, ProcessType.WEAPONS_PLATFORM_ASSEMBLY),
    "Vehicle::Facility::HeavyTank": (FacilityType.VEHICLE_FACTORY_2, ProcessType.HEAVY_TANK_ASSEMBLY),
    "Vehicle::Facility::Train::Base": (FacilityType.VEHICLE_FACTORY_2, ProcessType.DEFAULT),
    "Vehicle::Facility::Train::Advanced": (FacilityType.VEHICLE_FACTORY_2, ProcessType.TRAIN_ASSEMBLY),
    "Vehicle::MPF": (ProductionType.MPF, ProcessType.DEFAULT),
    "Vehicle::Garage": (ProductionType.GARAGE, ProcessType.DEFAULT),
    "Ship::MPF": (ProductionType.MPF, ProcessType.DEFAULT),
    "Ship::Shipyard": (ProductionType.SHIPYARD, ProcessType.DEFAULT),
    "Ship::Facility::NavalWorks": (FacilityType.VEHICLE_FACTORY_1, ProcessType.SHIP_ASSEMBLY),
    "Ship::Facility::Drydock": (FacilityType.VEHICLE_FACTORY_3, ProcessType.DEFAULT),
    "Uniform::Factory": (ProcessType.UNIFORMS, ProcessType.DEFAULT),
    "Uniform::Facility": (FacilityType.FACTORY_SMALL_ARMS, ProcessType.DEFAULT),
    "Uniform::MPF": (ProcessType.UNIFORMS, ProcessType.DEFAULT),
    "SmallArms::Facility": (FacilityType.FACTORY_SMALL_ARMS, ProcessType.INFANTRY_AMMO),
    "SmallArms::MPF": (ProcessType.SMALL_ARMS, ProcessType.DEFAULT),
    "SmallArms::Factory": (ProcessType.SMALL_ARMS, ProcessType.DEFAULT),
    "HeavyArms::Facility::SmallShell": (FacilityType.FACTORY_SMALL_ARMS, ProcessType.HEAVY_AMMO),
    "HeavyArms::Facility::InfantryAmmo": (FacilityType.FACTORY_SMALL_ARMS, ProcessType.INFANTRY_AMMO),
    "HeavyArms::MPF": (ProcessType.HEAVY_ARMS, ProcessType.DEFAULT),
    "HeavyArms::Factory": (FacilityType.FACTORY_AMMO, ProcessType.TRIPOD_FACTORY),
    "HeavyWeapons::Facility": (FacilityType.FACTORY_SMALL_ARMS, ProcessType.SPECIAL_WEAPONS),
    "HeavyAmmo::Facility::Base": (FacilityType.FACTORY_AMMO, ProcessType.DEFAULT),
    "HeavyAmmo::Facility::LargeShell": (FacilityType.FACTORY_AMMO, ProcessType.LARGE_SHELL_FACTORY),
    "HeavyAmmo::Facility::Rocket": (FacilityType.FACTORY_AMMO, ProcessType.ROCKET_FACTORY),
    "HeavyAmmo::Factory": (ProcessType.HEAVY_AMMO, ProcessType.DEFAULT),
    "HeavyAmmo::MPF": (ProcessType.HEAVY_AMMO, ProcessType.DEFAULT),
    "MaintenanceSupplies::Facility": (ProcessType.SUPPLIES, ProcessType.DEFAULT),
    "MaintenanceSupplies::MPF": (ProcessType.SUPPLIES, ProcessType.DEFAULT),
    "MaintenanceSupplies::Factory": (ProcessType.SUPPLIES, ProcessType.DEFAULT),
    "Utility::Factory": (ProcessType.UTILITY, ProcessType.DEFAULT),
    "Medical::Factory": (ProcessType.MEDICAL, ProcessType.DEFAULT),
    "Medical::Hospital": (ProcessType.MEDICAL, ProcessType.DEFAULT),
    "Medical::TrainHospital": (ProcessType.MEDICAL, ProcessType.DEFAULT),
    "Shippable::MPF": (ProcessType.UTILITY, ProcessType.DEFAULT),
    "Shippable::ConstructionYard": (ProductionType.CONSTRUCTION_YARD, ProcessType.DEFAULT),
    "Resource::Facility::BuildMaterials": (FacilityType.CONCRETE_MIXER, ProcessType.DEFAULT),
    "Resource::Facility::Coal::CokeT1": (FacilityType.REFINERY_COAL, ProcessType.DEFAULT),
    "Resource::Facility::Coal::CokeT2": (FacilityType.REFINERY_COAL, ProcessType.COKE_FURNACE),
    "Resource::Facility::Coal::OilConversionT1": (FacilityType.REFINERY_COAL, ProcessType.COAL_LIQUIFIER),
    "Resource::Facility::Coal::OilConversionT2": (FacilityType.REFINERY_COAL, ProcessType.ADVANCED_COAL_LIQUIFIER),
    "Resource::Facility::Oil::Raw": (FacilityType.MINE_OIL, ProcessType.DEFAULT),
    "Resource::Facility::Oil::PetrolT1": (FacilityType.REFINERY_OIL, ProcessType.DEFAULT),
    "Resource::Facility::Oil::PetrolT2": (FacilityType.REFINERY_OIL, ProcessType.REFORMER),
    "Resource::Facility::Oil::HeavyOil": (FacilityType.REFINERY_OIL, ProcessType.CRACKING_UNIT),
    "Resource::Facility::Oil::EnrichedOil": (FacilityType.REFINERY_OIL, ProcessType.PETROCHEMICAL_PLANT),
    "Resource::Refinery": (FacilityType.REFINERY, ProcessType.DEFAULT),
    "Material::Facility::MaterialFactory::Forge": (FacilityType.REFINERY_1, ProcessType.FORGE),
    "Material::Facility::MaterialFactory::MetalPress": (FacilityType.REFINERY_2, ProcessType.METAL_PRESS),
    "Material::Facility::MaterialFactory::Recycler": (FacilityType.REFINERY_2, ProcessType.RECYCLER),
    "Material::Facility::Metalworks::Base": (FacilityType.REFINERY_2, ProcessType.DEFAULT),
    "Material::Facility::Metalworks::BlastFurnace": (FacilityType.REFINERY_2, ProcessType.BLAST_FURNACE),
    "Material::Facility::Metalworks::Recycler": (FacilityType.REFINERY_2, ProcessType.RECYCLER),
    "Material::Facility::Metalworks::EngineeringStation": (FacilityType.REFINERY_2, ProcessType.ENGINEERING_STATION),
    "Power::Diseal": (FacilityType.POWER_DIESEL, ProcessType.DEFAULT),
    "Power::Coal": (FacilityType.POWER_DIESEL, ProcessType.COAL_LIQUIFIER),
    "Power::Petrol": (FacilityType.POWER_DIESEL, ProcessType.PETROCHEMICAL_PLANT),
    "Power::PowerStation": (FacilityType.POWER_OIL, ProcessType.DEFAULT),
    "Power::SulfuricReactor": (FacilityType.POWER_OIL, ProcessType.SULFURIC_REACTOR),
    "AdvancedStructure::Facility::RocketPlatform": (FacilityType.ROCKET_SITE, ProcessType.DEFAULT),
    "AdvancedStructure::Facility::AdvancedStructureManufactory": (FacilityType.VEHICLE_FACTORY_1, ProcessType.ROCKET_ASSEMBLY),
}

